name: Pull Request Notify
run-name: Send pull request notification
on: workflow_dispatch
jobs:
  Check_User_Merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checking User Pull Request
        run: |
         curl -X POST -H 'Content-type: application/json' --data '{"text":"Hello, World!"}' ${{secrets.SLACK_WEBHOOK_URL}}
