name: Pull Request Notify
run-name: Send pull request notification
on: workflow_dispatch
jobs:
  Check_User_Merge:
    runs-on: ubuntu-latest
    steps:
     - name : Checking User Pull Request
       run: echo started by "${{github.event.pull_request.author_association}}"
     - name: Send Notification to Slack
       run: |
          echo "Sending Slack notification..."
          curl -X POST -H 'Content-type: application/json' --data '{"text":" on *${{ github.repository }}* pull requested by  *${{ github.actor}}* that role is  ${{github.event.pull_request.author_association}}  "}' ${{secrets.SLACK_WEBHOOK_URL}}
 
