name: Pull Request Notify
run-name: Send pull request notification
on: workflow_dispatch
jobs:
  Check_User_Merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checking User Pull Request
        run: echo "Started by ${{secrets.DEMO}}"
